apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: default
spec:
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - image: isdance/client:v-43
          imagePullPolicy: IfNotPresent
          name: web
          ports:
            - containerPort: 80
              protocol: TCP
